name: project_flutter2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.4
  http: 0.13.2
  shared_preferences: 2.0.12
  flutter_screenutil: 5.2.0
  #firebase_messaging: 11.2.6
  #flutter_local_notifications: 9.3.2
  platform_device_id: 1.0.1
  timeago: 3.2.2
  intl: 0.17.0
  permission_handler: 9.0.2
  video_player: 2.3.0
  url_launcher: 6.0.10
  flutter_bloc: 8.0.0
  #package_info_plus: 1.2.0
  sentry_flutter: 6.2.2
  flutter_html: 2.2.0
  carousel_slider: 4.0.0
  qr_code_scanner: 0.6.1
  flutter_staggered_grid_view: 0.6.0
  reorderable_grid_view: 2.2.2
 # firebase_auth: 3.3.8
 # firebase_dynamic_links: 4.0.6
 # share: 2.0.0
  external_app_launcher: 2.0.2
 # momo_vn: 2.0.1
 # flutter_zalopay_sdk: 0.1.4
 # flutter_hl_vnpay: 2.0.1
 # sprintf: 6.0.0
 # http_auth: 1.0.1
  image: 3.1.2
  image_picker: 0.8.4+10
  file_picker: 4.5.0
  downloads_path_provider_28: 0.1.2
  path_provider: 2.0.4
 # sign_in_with_apple: 3.2.0
 # google_sign_in: 5.2.4
 # flutter_facebook_auth: 4.1.2
  flutter_datetime_picker: 1.5.1
  change_app_package_name: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/theme3/
    - assets/jsons/
    - assets/fonts/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
